### ISSUE TITLE
Which version (haxelib or github repo) do I use for the current version of Haxe (3.2.1)

### ISSUE THREAD

**Issue by dionjwa** [haxetink/tink_macro#4]
I'm getting some compile errors on very simple examples, e.g. from the github repo:

server/common/lib/tinkerbell/src/tink/macro/tools/ExprTools.hx:53: characters 8-27 : Class<haxe.macro.Context> has no field getPosInfos

The haxelib version documentation seems out of date. So which version do you recommend for the current version of Haxe (3.2.1)?

Thanks!

**Comment by back2dos** [comment]
The git and haxelib versions are currently in sync. Can you please elaborate on what exactly seems out of date?

The problem itself would seem to come from the fact that you have tink_macro classes leak out of the macro context, where they don't compile, because Context.getPosInfos is not available outside macro context. You need to put your imports between `#if macro` and it should work.

**Comment by back2dos** [comment]
I assume this is no longer an issue. Otherwise please get back to me with more details ;)
